<div style="padding: 5px;font-family:微软雅黑;">
<table class="tableForm" width="100%">
	<tr>
		<th>id:</th>
		<td>${app.id}</td>
	</tr>					
	<tr>
		<th width="25%">create_time:</th>
		<td>${app.createTime}</td>
	</tr>					
	<tr>
		<th>update_time:</th>
		<td>${app.updateTime}</td>
	</tr>					
	<tr>
		<th>display_name:</th>
		<td>${app.displayName}</td>
	</tr>					
	<tr>
		<th>name:</th>
		<td>${app.name}</td>
	</tr>					
	<tr>
		<th>parent_app_id:</th>
		<td>${app.parentAppId}</td>
	</tr>					
	<tr>
		<th>parent_id:</th>
		<td>${app.parentId}</td>
	</tr>					
	<tr>
		<th>raw_add_time:</th>
		<td>${app.rawAddTime}</td>
	</tr>					
	<tr>
		<th>raw_update_time:</th>
		<td>${app.rawUpdateTime}</td>
	</tr>					
	<tr>
		<th>type:</th>
		<td>${app.type}</td>
	</tr>					
	<tr>
		<th>user_id:</th>
		<td>${app.userId}</td>
	</tr>					
	<tr>
		<th>price:</th>
		<td>${app.price}</td>
	</tr>					
</table>
</div>
